<a href="https://colab.research.google.com/github/Mileej/Proyecto_individual/blob/main/Proyecto2_MovilidadMedell%C3%ADn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

FUENTE DE LOS DATOS

**Incidentes de movilidad Medellín**
tomado de: https://geomedellin-m-medellin.opendata.arcgis.com/datasets/M-Medellin::incidentes-georreferenciados-2022-gdb/explore?location=6.247704%2C-75.588628%2C12.68

Descripción: Los datos presentan información de accidentes de tránsitod registrados por la Secretaría de movilidad de la Alcaldía de Medellín, en el año 2022

In [5]:
import pandas as pd

In [3]:
df=pd.read_csv('/content/drive/MyDrive/Semestre 2022-2/CODING_DOJO_DS/Advanced_ML/Proyecto 2/movilidad_incidentes_2022_gdb.csv')
df.head()

,X,Y,OBJECTID,RADICADO,HORA,DIA_NOMBRE,PERIODO,CLASE,DIRECCION,DIRECCION_ENC,...,COMUNA,DISENO,MES,DIA,FECHA,MES_NOMBRE,X_MAGNAMED,Y_MAGNAMED,LONGITUD,LATITUD
0,-75.592351,6.243512,1,1783170,08:05:00,MIÉRCOLES,2022,Choque,Circular 2 Con Carrera 74,CQ 002 074 000 00000,...,Laureles Estadio,Interseccion,3,16,2022/03/16 00:00:00+00,MARZO,832338.65,1182399.08,-75.592351,6.243512
1,-75.579832,6.230514,2,1783476,17:30:00,MIÉRCOLES,2022,Choque,Carrera 55 Con Calle 29 C,CR 055 029 C 000 00000,...,Guayabal,Interseccion,3,16,2022/03/16 00:00:00+00,MARZO,833724.32,1180961.28,-75.579832,6.230514
2,-75.599001,6.269136,3,1789709,17:00:00,MIÉRCOLES,2022,Choque,Calle 54 Con Carrera 83,CL 054 083 000 00000,...,San Javier,Interseccion,5,4,2022/05/04 00:00:00+00,MAYO,831602.70,1185233.45,-75.599001,6.269136
3,-75.573979,6.232882,4,1793934,13:30:00,DOMINGO,2022,Choque,Carrera 49 Con Calle 31,CR 049 031 000 00000,...,La Candelaria,Tramo de via,6,12,2022/06/12 00:00:00+00,JUNIO,834372.23,1181223.19,-75.573979,6.232882
4,-75.703816,6.221806,5,1791043,06:45:00,MIÉRCOLES,2022,Otro,Carrera 30 Con Calle 8 A,0,...,NaN,Lote o Predio,5,18,2022/05/18 00:00:00+00,MAYO,820000.00,1180000.00,-75.703816,6.221806

Objetivo: Predecir la graverdad de los accidentes ocurridos en este año y como se relaciona con las variables como tipo de accidente, ubicación el accidente, el dia, el barrio y las otras variables pertinentes

# Exploración inicial

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23577 entries, 0 to 23576
Data columns (total 25 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   X              23577 non-null  float64
 1   Y              23577 non-null  float64
 2   OBJECTID       23577 non-null  int64
 3   RADICADO       23577 non-null  int64
 4   HORA           23577 non-null  object
 5   DIA_NOMBRE     23577 non-null  object
 6   PERIODO        23577 non-null  int64
 7   CLASE          23577 non-null  object
 8   DIRECCION      23577 non-null  object
 9   DIRECCION_ENC  23577 non-null  object
 10  CBML           23577 non-null  object
 11  TIPO_GEOCOD    23577 non-null  object
 12  EXPEDIENTE     23577 non-null  object
 13  GRAVEDAD       23577 non-null  object
 14  BARRIO         21794 non-null  object
 15  COMUNA         21794 non-null  object
 16  DISENO         23577 non-null  object
 17  MES            23577 non-null  int64
 18  DIA            23577 non-null  int64
 19  FECHA          23577 non-null  object
 20  MES_NOMBRE     23577 non-null  object
 21  X_MAGNAMED     23577 non-null  float64
 22  Y_MAGNAMED     23577 non-null  float64
 23  LONGITUD       23577 non-null  float64
 24  LATITUD        23577 non-null  float64
dtypes: float64(6), int64(5), object(14)
memory usage: 4.5+ MB

In [7]:
df.columns

Index(['X', 'Y', 'OBJECTID', 'RADICADO', 'HORA', 'DIA_NOMBRE', 'PERIODO',
       'CLASE', 'DIRECCION', 'DIRECCION_ENC', 'CBML', 'TIPO_GEOCOD',
       'EXPEDIENTE', 'GRAVEDAD', 'BARRIO', 'COMUNA', 'DISENO', 'MES', 'DIA',
       'FECHA', 'MES_NOMBRE', 'X_MAGNAMED', 'Y_MAGNAMED', 'LONGITUD',
       'LATITUD'],
      dtype='object')

In [8]:
#Eliminar columnas que no considere necesario
df=df.drop(columns=['X','Y','OBJECTID','RADICADO','X_MAGNAMED','Y_MAGNAMED','LONGITUD','LATITUD'])

In [9]:
df

,HORA,DIA_NOMBRE,PERIODO,CLASE,DIRECCION,DIRECCION_ENC,CBML,TIPO_GEOCOD,EXPEDIENTE,GRAVEDAD,BARRIO,COMUNA,DISENO,MES,DIA,FECHA,MES_NOMBRE
0,08:05:00,MIÉRCOLES,2022,Choque,Circular 2 Con Carrera 74,CQ 002 074 000 00000,1107,Malla vial,A001423465,HERIDO,Bolivariana,Laureles Estadio,Interseccion,3,16,2022/03/16 00:00:00+00,MARZO
1,17:30:00,MIÉRCOLES,2022,Choque,Carrera 55 Con Calle 29 C,CR 055 029 C 000 00000,1502,Malla vial,A001423492,MUERTO,Tenche,Guayabal,Interseccion,3,16,2022/03/16 00:00:00+00,MARZO
2,17:00:00,MIÉRCOLES,2022,Choque,Calle 54 Con Carrera 83,CL 054 083 000 00000,1301,Malla vial,A001429452,SOLO DAÑOS,El Pesebre,San Javier,Interseccion,5,4,2022/05/04 00:00:00+00,MAYO
3,13:30:00,DOMINGO,2022,Choque,Carrera 49 Con Calle 31,CR 049 031 000 00000,1012,Malla vial aproximada: CR 48-31,A001433803,HERIDO,Perpetuo Socorro,La Candelaria,Tramo de via,6,12,2022/06/12 00:00:00+00,JUNIO
4,06:45:00,MIÉRCOLES,2022,Otro,Carrera 30 Con Calle 8 A,0,Sin inf,No Ubicada,A001430922,HERIDO,NaN,NaN,Lote o Predio,5,18,2022/05/18 00:00:00+00,MAYO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23572,10:30:00,VIERNES,2022,Otro,Calle 80 Con Carrera 95 AA,CL 080 095 AA 000 00000,0712,Malla vial cruce invertido,A001425381,HERIDO,Aures No. 2,Robledo,Lote o Predio,4,1,2022/04/01 00:00:00+00,ABRIL
23573,16:55:00,SÁBADO,2022,Atropello,Carrera 50 A Con Calle 53,CR 050 A 053 000 00000,1019,Malla vial,A001488031,HERIDO,La Candelaria,La Candelaria,Lote o Predio,7,16,2022/07/16 00:00:00+00,JULIO
23574,13:40:00,MIÉRCOLES,2022,Otro,Carrera 52 Con Calle 29,CR 052 029 000 00000,1504,Malla vial,A001430166,HERIDO,Santa Fé,Guayabal,Lote o Predio,5,11,2022/05/11 00:00:00+00,MAYO
23575,03:00:00,MIÉRCOLES,2022,Choque,Carrera 46 Con Calle 85,CR 046 085 000 00000,0411,Malla vial,A001415651,SOLO DAÑOS,Las Esmeraldas,Aranjuez,Tramo de via,1,5,2022/01/05 00:00:00+00,ENERO
23576,21:30:00,MARTES,2022,Otro,Carrera 22 Con Calle 16,CR 022 016 000 00000,9083,Malla vial,A001428278,HERIDO,Suburbano Mirador del Poblado,Corregimiento de Santa Elena,Tramo de via,4,26,2022/04/26 00:00:00+00,ABRIL

In [18]:
#descartemos otras dos filas: periodo y Fecha y mes_nombre y  ya que los datos son de 2022 y los meses y los dias están separados y en el caso del mes esta de manera númerica
#Nota: CBML -->Se refiere a la unión del COBAMA (Comuna, Barrio, Manzana) y el número de lote, abreviado como "CBML". 
df=df.drop(columns=['PERIODO','MES_NOMBRE','FECHA'])
df.head()

,HORA,DIA_NOMBRE,CLASE,DIRECCION,DIRECCION_ENC,CBML,TIPO_GEOCOD,EXPEDIENTE,GRAVEDAD,BARRIO,COMUNA,DISENO,MES,DIA
0,08:05:00,MIÉRCOLES,Choque,Circular 2 Con Carrera 74,CQ 002 074 000 00000,1107,Malla vial,A001423465,HERIDO,Bolivariana,Laureles Estadio,Interseccion,3,16
1,17:30:00,MIÉRCOLES,Choque,Carrera 55 Con Calle 29 C,CR 055 029 C 000 00000,1502,Malla vial,A001423492,MUERTO,Tenche,Guayabal,Interseccion,3,16
2,17:00:00,MIÉRCOLES,Choque,Calle 54 Con Carrera 83,CL 054 083 000 00000,1301,Malla vial,A001429452,SOLO DAÑOS,El Pesebre,San Javier,Interseccion,5,4
3,13:30:00,DOMINGO,Choque,Carrera 49 Con Calle 31,CR 049 031 000 00000,1012,Malla vial aproximada: CR 48-31,A001433803,HERIDO,Perpetuo Socorro,La Candelaria,Tramo de via,6,12
4,06:45:00,MIÉRCOLES,Otro,Carrera 30 Con Calle 8 A,0,Sin inf,No Ubicada,A001430922,HERIDO,NaN,NaN,Lote o Predio,5,18

In [19]:
#otras columnas que podemos descartar 
df=df.drop(columns=['DIRECCION_ENC','EXPEDIENTE'])
df.head()

,HORA,DIA_NOMBRE,CLASE,DIRECCION,CBML,TIPO_GEOCOD,GRAVEDAD,BARRIO,COMUNA,DISENO,MES,DIA
0,08:05:00,MIÉRCOLES,Choque,Circular 2 Con Carrera 74,1107,Malla vial,HERIDO,Bolivariana,Laureles Estadio,Interseccion,3,16
1,17:30:00,MIÉRCOLES,Choque,Carrera 55 Con Calle 29 C,1502,Malla vial,MUERTO,Tenche,Guayabal,Interseccion,3,16
2,17:00:00,MIÉRCOLES,Choque,Calle 54 Con Carrera 83,1301,Malla vial,SOLO DAÑOS,El Pesebre,San Javier,Interseccion,5,4
3,13:30:00,DOMINGO,Choque,Carrera 49 Con Calle 31,1012,Malla vial aproximada: CR 48-31,HERIDO,Perpetuo Socorro,La Candelaria,Tramo de via,6,12
4,06:45:00,MIÉRCOLES,Otro,Carrera 30 Con Calle 8 A,Sin inf,No Ubicada,HERIDO,NaN,NaN,Lote o Predio,5,18

In [20]:
df.isna().sum() #los datos faltantes los llenaremos con algunas metricas.

HORA              0
DIA_NOMBRE        0
CLASE             0
DIRECCION         0
CBML              0
TIPO_GEOCOD       0
GRAVEDAD          0
BARRIO         1783
COMUNA         1783
DISENO            0
MES               0
DIA               0
dtype: int64

In [28]:
#revisión de duplicados 
df.duplicated().sum()

11

In [29]:
#eliminar duplicados 
df=df.drop_duplicates()
df

,HORA,DIA_NOMBRE,CLASE,DIRECCION,CBML,TIPO_GEOCOD,GRAVEDAD,BARRIO,COMUNA,DISENO,MES,DIA
0,08:05:00,MIÉRCOLES,Choque,Circular 2 Con Carrera 74,1107,Malla vial,HERIDO,Bolivariana,Laureles Estadio,Interseccion,3,16
1,17:30:00,MIÉRCOLES,Choque,Carrera 55 Con Calle 29 C,1502,Malla vial,MUERTO,Tenche,Guayabal,Interseccion,3,16
2,17:00:00,MIÉRCOLES,Choque,Calle 54 Con Carrera 83,1301,Malla vial,SOLO DAÑOS,El Pesebre,San Javier,Interseccion,5,4
3,13:30:00,DOMINGO,Choque,Carrera 49 Con Calle 31,1012,Malla vial aproximada: CR 48-31,HERIDO,Perpetuo Socorro,La Candelaria,Tramo de via,6,12
4,06:45:00,MIÉRCOLES,Otro,Carrera 30 Con Calle 8 A,Sin inf,No Ubicada,HERIDO,NaN,NaN,Lote o Predio,5,18
...,...,...,...,...,...,...,...,...,...,...,...,...
23572,10:30:00,VIERNES,Otro,Calle 80 Con Carrera 95 AA,0712,Malla vial cruce invertido,HERIDO,Aures No. 2,Robledo,Lote o Predio,4,1
23573,16:55:00,SÁBADO,Atropello,Carrera 50 A Con Calle 53,1019,Malla vial,HERIDO,La Candelaria,La Candelaria,Lote o Predio,7,16
23574,13:40:00,MIÉRCOLES,Otro,Carrera 52 Con Calle 29,1504,Malla vial,HERIDO,Santa Fé,Guayabal,Lote o Predio,5,11
23575,03:00:00,MIÉRCOLES,Choque,Carrera 46 Con Calle 85,0411,Malla vial,SOLO DAÑOS,Las Esmeraldas,Aranjuez,Tramo de via,1,5
23576,21:30:00,MARTES,Otro,Carrera 22 Con Calle 16,9083,Malla vial,HERIDO,Suburbano Mirador del Poblado,Corregimiento de Santa Elena,Tramo de via,4,26

In [30]:
df.duplicated().sum()

0

Veamos algunas variables categóricas

In [22]:
df['CLASE'].value_counts()

Choque            15442
Otro               5167
Atropello          2073
Caida Ocupante      703
Volcamiento         188
Incendio              4
Name: CLASE, dtype: int64

In [23]:
df['TIPO_GEOCOD'].value_counts()

Malla vial                          18211
No Ubicada                           2283
Malla vial cruce invertido            508
EPM sin Interior                      413
EPM con Interior                      232
                                    ...
Malla vial aproximada: CL 65-108        1
Malla vial aproximada: CR 47-112        1
Malla vial aproximada: CR 89-31         1
Malla vial aproximada: CR 33-35         1
Malla vial aproximada: CL 67-53         1
Name: TIPO_GEOCOD, Length: 825, dtype: int64

In [24]:
df['DISENO'].value_counts()

Tramo de via     12311
Lote o Predio     5643
Interseccion      4620
Glorieta           474
Paso Elevado       151
Ciclo Ruta         105
Puente             105
Paso Inferior      100
Tunel               46
Paso a Nivel        13
Pontón               5
Via peatonal         4
Name: DISENO, dtype: int64

In [25]:
df['GRAVEDAD'].value_counts()

HERIDO        13671
SOLO DAÑOS     9777
MUERTO          129
Name: GRAVEDAD, dtype: int64